# ============================================================================ 
# Group: 19
# Team Members:
# - Youssef Ekrami Elsayed 
# - Abdelrahman Mohamed Negm
# - Hagar Mohamed Badawy
# - Dareen Ashraf Mosa
# ============================================================================

# -*- coding: utf-8 -*-
"""Collaborative

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNl1-C_fNCLfO1gX2QQawF1HI8AHjl_S

Part 3: Collaborative Filtering

8.Collaborative Filtering Integration

8.1. Implement ONE CF approach: User-based OR Item-based CF
"""

import pandas as pd
import numpy as np
import os
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse.linalg import svds

# Define relative paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR = os.path.join(BASE_DIR, "SECTION2_DomainRecommender", "data")
RESULTS_DIR = os.path.join(BASE_DIR, "SECTION2_DomainRecommender", "results")
CODE_DIR = os.path.join(BASE_DIR, "SECTION2_DomainRecommender", "code")

DATASET_PATH = os.path.join(DATA_DIR, "cleaned_financial_data.csv")
TABLES_DIR = os.path.join(RESULTS_DIR, "tables", "CollaborativeFiltering")
PLOTS_DIR = os.path.join(RESULTS_DIR, "plots", "CollaborativeFiltering")

# Create directories if they don't exist
os.makedirs(TABLES_DIR, exist_ok=True)
os.makedirs(PLOTS_DIR, exist_ok=True)

# Load dataset
df = pd.read_csv(DATASET_PATH)

user_item_matrix = df.pivot_table(
    index="user_id",
    columns="item_id",
    values="rating"
)

user_item_matrix_filled = user_item_matrix.fillna(0)

item_similarity = cosine_similarity(user_item_matrix_filled.T)

item_similarity_df = pd.DataFrame(
    item_similarity,
    index=user_item_matrix.columns,
    columns=user_item_matrix.columns
)

item_similarity_df.head()

user_item_matrix = df.pivot_table(
    index='user_id',
    columns='item_id',
    values='rating'
)

user_item_matrix.head()

def item_based_recommendation(user_id, top_n=5):
    if user_id not in user_item_matrix.index:
        return []

    user_ratings = user_item_matrix.loc[user_id]
    rated_items = user_ratings[user_ratings > 0].index

    scores = {}

    for item in rated_items:
        similar_items = item_similarity_df[item]

        for sim_item, sim_score in similar_items.items():
            if sim_item not in rated_items:
                if sim_item not in scores:
                    scores[sim_item] = 0
                scores[sim_item] += sim_score * user_ratings[item]

    scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    return scores[:top_n]

item_based_recommendation(user_id=10, top_n=5)

recommendations = item_based_recommendation(10, 5)

result_df = pd.DataFrame(
    recommendations,
    columns=["recommended_item", "score"]
)

# Save results with relative path
result_df.to_csv(
    os.path.join(TABLES_DIR, "item_based_cf_result.csv"),
    index=False
)

result_df

"""8.2. Use matrix factorization from SECTION 1:

Apply SVD with k=10  latent factors
"""

# Note: We need to use the same dataset as above
df = pd.read_csv(DATASET_PATH)

user_item_matrix = df.pivot_table(
    index="user_id",
    columns="item_id",
    values="rating"
)

# Fill missing values with 0
user_item_filled = user_item_matrix.fillna(0)

k = 10

U, sigma, Vt = svds(user_item_filled.values, k=k)

sigma = np.diag(sigma)

predicted_ratings = np.dot(np.dot(U, sigma), Vt)

predicted_df = pd.DataFrame(
    predicted_ratings,
    index=user_item_matrix.index,
    columns=user_item_matrix.columns
)

predicted_df.head()

def svd_recommendation(user_id, top_n=5):
    if user_id not in predicted_df.index:
        return []

    user_predictions = predicted_df.loc[user_id]
    user_actual = user_item_matrix.loc[user_id]

    # Recommend items not yet rated
    recommendations = user_predictions[user_actual.isna()]

    recommendations = recommendations.sort_values(ascending=False)

    return recommendations.head(top_n)

svd_recommendation(user_id=10, top_n=5)

result_df = svd_recommendation(10, 5).reset_index()
result_df.columns = ["recommended_item", "predicted_rating"]

# Save results with relative path
result_df.to_csv(
    os.path.join(TABLES_DIR, "svd_recommendations_10.csv"),
    index=False
)

result_df